# Generated by Django 4.0.5 on 2022-07-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiar', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('años', models.IntegerField()),
            ],
        ),
    ]
